spring.application.name=CRUD-testing-with-db
server.port=9191

spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/test_crud_db
#spring.datasource.username = mysql_user
#spring.datasource.password = mysql123
#
#spring.sql.init.schema-locations= classpath:/test/schema.sql
#spring.sql.init.data-locations= classpath:/test/data.sql
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
